#!/usr/bin/env bash
#
# generate_docs_index.sh — regenerate docs/solutions/INDEX.md from the frontmatter
# of every solution write-up. Groups by category (module) and orders by severity,
# with a trailing "Archived / superseded" section for retired docs.
#
# Frontmatter is parsed with a REAL YAML parser and the index is built from that
# mapping, so malformed frontmatter fails the run (with the file path) instead of
# being silently masked. PyYAML is taken from the vendored Dotbot submodule when
# system Python doesn't have it, so there is no extra dependency to install; if
# neither is importable the run FAILS CLOSED rather than degrading to a weaker
# parser.
#
# DETERMINISTIC by construction: stable sorts, no timestamps in the output — run
# it twice and `git diff` is empty. Run from the repo root:
#   helpers/generate_docs_index.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

python3 - <<'PY'
import glob, os, re, sys

SOL = "docs/solutions"
INDEX = os.path.join(SOL, "INDEX.md")
SEV_RANK = {"High": 0, "Medium": 1, "Low": 2, "Informational": 3, "": 4}
ARCHIVED = {"retired", "superseded", "abandoned", "deprecated"}

# Real YAML parser, fail-closed. Prefer the vendored Dotbot copy so a clean
# system Python without PyYAML still works; only error out if neither is present.
sys.path.insert(0, os.path.join(REPO := os.getcwd(), "dotbot", "lib", "pyyaml", "lib"))
try:
    import yaml
except ImportError:
    sys.stderr.write("ERROR: PyYAML not importable (system or vendored dotbot copy) — "
                     "cannot validate frontmatter; refusing to generate a possibly-wrong index.\n")
    sys.exit(1)

def frontmatter(path):
    m = re.match(r"^---\n(.*?)\n---\n", open(path, encoding="utf-8").read(), re.S)
    if not m:
        raise ValueError(f"{path}: no YAML frontmatter block")
    try:
        d = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        raise ValueError(f"{path}: invalid YAML frontmatter — {str(e).splitlines()[0]}")
    if not isinstance(d, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return d

docs = []
errors = []
for path in glob.glob(f"{SOL}/**/*.md", recursive=True):
    if os.path.basename(path) == "INDEX.md":
        continue
    try:
        d = frontmatter(path)
    except ValueError as e:
        errors.append(str(e)); continue
    rel = os.path.relpath(path, SOL)
    if "module" not in d:
        errors.append(f"{path}: missing required 'module' field"); continue
    docs.append({
        "rel": rel,
        "title": str(d.get("title", os.path.splitext(os.path.basename(path))[0])),
        "module": str(d["module"]),
        "category": str(d.get("category") or rel.split(os.sep)[0]),
        "severity": str(d.get("severity", "")),
        "date": str(d.get("date", "")),
        "status": str(d.get("status", "")),
    })

if errors:
    sys.stderr.write("ERROR: invalid solution frontmatter:\n  " + "\n  ".join(errors) + "\n")
    sys.exit(1)

active = [d for d in docs if d["status"].lower() not in ARCHIVED]
archived = [d for d in docs if d["status"].lower() in ARCHIVED]

def _neg(s):  # invert a string so dates sort DESCending within a severity
    return "".join(chr(0x10FFFF - ord(c)) for c in s)

def sort_key(d):
    return (SEV_RANK.get(d["severity"], 4), _neg(d["date"]), d["title"].lower())

def row(d):
    return f"| {d['severity'] or '—'} | [{d['title']}]({d['rel']}) | {d['date'] or '—'} |"

out = ["# Solutions index", ""]
out.append(f"{len(active)} active write-up(s)"
           + (f", {len(archived)} archived" if archived else "")
           + ". Grouped by module, ordered by severity.")
out += ["", "> Generated by `helpers/generate_docs_index.sh` — do not edit by hand; "
            "re-run the generator instead.", ""]

for mod in sorted({d["module"] for d in active}, key=str.lower):
    items = sorted([d for d in active if d["module"] == mod], key=sort_key)
    out += [f"## {mod}", "", "| Severity | Write-up | Date |", "|---|---|---|"]
    out += [row(d) for d in items]
    out.append("")

if archived:
    out += ["## Archived / superseded", "", "| Status | Write-up | Date |", "|---|---|---|"]
    for d in sorted(archived, key=lambda d: (d["category"], d["title"].lower())):
        out.append(f"| {d['status']} | [{d['title']}]({d['rel']}) | {d['date'] or '—'} |")
    out.append("")

open(INDEX, "w", encoding="utf-8").write("\n".join(out).rstrip() + "\n")
print(f"wrote {INDEX}: {len(active)} active, {len(archived)} archived, "
      f"{len({d['module'] for d in active})} modules")
PY
