tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "saulpw/vd"
# Search tool like grep, but optimized for programmers
brew "ack"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Authenticate with AWS using your Okta credentials
brew "aws-okta"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Distributed revision control system
brew "git"
# Small git utilities
brew "git-extras"
# Interpreted, interactive, object-oriented programming language
brew "python"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# X.509 and CMS library
brew "libksba"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Colorize logfiles and command output
brew "grc"
# Bash and zsh history suggest box
brew "hstr"
# Improved top (interactive process viewer)
brew "htop"
# Audio and video processing tools
brew "libav"
# Generic library support script
brew "libtool"
# Powerful, lightweight programming language
brew "lua"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Data compression library
brew "lzlib"
# Mac App Store command-line interface
brew "mas"
# Open source relational database management system
brew "mysql"
# Tiny, lightning fast, feature-packed file manager
brew "nnn"
# Display the PID number for a given process name
brew "pidof"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# CPU/RAM/battery stats chart bar for tmux (and GNU screen)
brew "rainbarf"
# Ruby version manager
brew "rbenv"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# File system client based on SSH File Transfer Protocol
brew "sshfs"
# Code-search similar to ack
brew "the_silver_searcher"
# Text interface for Git repositories
brew "tig"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Extract, view, and test RAR archives
brew "unrar"
# Vi 'workalike' with many additional features
brew "vim"
# Pager/text based browser
brew "w3m"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Terminal utility for exploring and arranging tabular data
brew "saulpw/vd/visidata"
mas "1Password 7", id: 1333542190
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste", id: 967805235
mas "Pocket", id: 568494494
mas "Simplenote", id: 692867256
mas "Spark", id: 1176895641
mas "TickTick", id: 966085870
mas "Xcode", id: 497799835
