#!/usr/bin/env zsh

# Add basic PATH stuff
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Add brew curl first to path
export PATH="/usr/local/opt/curl/bin:$PATH"

# Add MySQL to path
export PATH="$PATH:/usr/local/mysql/bin"

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# Add Yarn to PATH
export PATH="$PATH:$HOME/.yarn/bin"

# Add GNU coreutils to PATH
#export PATH="$PATH:/usr/local/opt/coreutils/libexec/gnubin"

# Add Rust bin to PATH
export PATH="$PATH:$HOME/.cargo/bin";

# Add my experimental stuff to PATH
export PATH="$PATH:$HOME/bin";
export PATH="$PATH:$HOME/.local/bin";

# Export openssl compiler flags
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
